### ISSUE TITLE
Could not find module `@ember/version` imported from `ember-uploader/index`

### ISSUE THREAD

**Issue by Kernes** [benefitcloud/ember-uploader#174] opened 2018-06-07 14:01 UTC
Hi,

I’m using Ember v2.18 and ember-uploader v1.3.0.

When I navigate to a page using the uploader component, I get the following error in the console:

`Could not find module @ember/version imported from ember-uploader/index`

Do you have any idea how I can fix this?

Thanks!

**Comment by Dhaulagiri** [comment] 2018-06-07 14:22
@Kernes out of curiosity, what version of ember-cli-babel are you using in your package.json?

**Comment by Kernes** [comment] 2018-06-07 14:27
Hi @Dhaulagiri,

I’m using v6.6, my package.json contains `"ember-cli-babel": "^6.6.0"` and all node packages are up-to-date.

**Comment by Dhaulagiri** [comment] 2018-06-07 14:31
@snewcomer the way that this addon exports itself seems a little non-standard so I am a little confused in this case, but I suspect that we might not be able to use the new modules syntax. Any thoughts?

**Comment by snewcomer** [comment] 2018-06-07 15:01
@Kernes which module couldn't it import?

`Could not find module imported from ember-uploader/index`

@Dhaulagiri Yeah it totally is. Good catch! 👍 I would be in favor of removing the version checker and adding those exports so they are merged into the consuming application's namespace!

**Comment by Dhaulagiri** [comment] 2018-06-07 15:12
Yeah the version checker seems unnecessary to me, so +1 to removing it regardless.

**Comment by Kernes** [comment] 2018-06-07 15:13
@snewcomer i edited my message. it's @ember/version

**Comment by Dhaulagiri** [comment] 2018-06-08 18:03
@Kernes can you try 1.3.1 and see if it corrects your issue?

**Comment by Kernes** [comment] 2018-06-09 08:57
It seem like good for this error, but now i have the error :
`Uncaught Error: Could not find module @ember/application/namespace imported from ember-uploader/core`

**Comment by Dhaulagiri** [comment] 2018-06-09 14:10
@Kernes I was able to reproduce this locally for a brief moment before accidentally fixing it.  I _think_ what might have been happening is that I had a stale node_modules folder for the addon which did not have a current version of ember-cli-babel referenced. Can you run `npm ls ember-cli-babel` locally and see what version `ember-uploader` is using?

**Comment by snewcomer** [comment] 2018-06-09 14:45
@Dhaulagiri My understanding is `@ember` syntax is only safe if it is in the addon folder and reexported.  I suspect this has to do with what you pointed out earlier this week.

**Comment by Kernes** [comment] 2018-06-09 15:21
@Dhaulagiri `ember-cli-babel@6.14.1`

**Comment by Dhaulagiri** [comment] 2018-06-09 16:14
@snewcomer that is generally true but wouldn’t explain how I was able to reproduce it. 

In any event, the easiest solution is probably to undo the modules import changes that were made since they don’t actually provide any benefit, and then subsequently we can do the modules change and fix the export problems in a major version change.

**Comment by Dhaulagiri** [comment] 2018-06-09 18:52
@Kernes if you are able to, can you point your package.json to `benefit-cloud/ember-uploader#br-modules` and see if that corrects the problem?

**Comment by simonc** [comment] 2018-06-10 07:15
Hi @Dhaulagiri.

I'm working with @Kernes. Sadly ember-uploader was the last package to prevent a massive dependencies update and it was blocking the entire team. Since we were already using ember-file-upload in other parts of our app we decided to rewrite the problematic section and got rid of ember-uploader. We won't be able to answer any further questions 😞

We'd like to thank you for your reactivity though and would be happy to try ember-uploader again in a future project 😊

**Closed** 2018-06-10 13:11 UTC
