### ISSUE TITLE
Initial Installation Fails

### ISSUE THREAD

**Issue by ghost** [benefitcloud/ember-uploader#140] opened 2016-12-09 15:29 UTC
Either the docs aren't clear enough or there is something breaking in Ember-Cli v2.10.

```js
loader.js:239 Uncaught Error: Could not find module `ember-uploader` imported from `project/components/file-upload`
```

Component:
```js
import Ember from 'ember';
import EmberUploader from 'ember-uploader';

export default EmberUploader.FileField.extend({
  filesDidChange: function(files) {
    const uploader = EmberUploader.Uploader.create({
      url: this.get('url')
    });

    if (!Ember.isEmpty(files)) {
      // this second argument is optional and can to be sent as extra data with the upload
      uploader.upload(files[0], { whateverObject });
    }
  }
});
```

Template: 
```hbs
{{file-upload url="/upload"}}
```

**Comment by digitaltoad** [comment] 2016-12-09 15:43
I'm not able to reproduce this. Any other information you could give on the problem?

**Comment by mpash** [comment] 2016-12-09 20:27
That is the extent of what I know. I'll try and create a new app and see if it works. Are you sure that is all I need to change for this work?

**Comment by digitaltoad** [comment] 2016-12-11 19:13
How have you installed the addon?

**Comment by mpash** [comment] 2016-12-13 00:50
I called `ember install ember-uploader`, and created the component coded above, and added the template helper per the name of the component with the `url` property. Is there something I'm missing? Do I need to import something in my `ember-cli-build.js` with `app.import()`?

**Comment by digitaltoad** [comment] 2016-12-13 16:04
There is nothing else required. What version of `ember-uploader` are you using?

**Comment by Dhaulagiri** [comment] 2018-06-02 14:28
Closing due to age but please re-open if this is still a problem

**Closed by Dhaulagiri** 2018-06-02 14:28 UTC
